---
- name: Install and Configure BIND9 DNS Server
  hosts: ubuntu_hosts
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install BIND9 DNS Server
      apt:
        name: bind9
        state: present

    - name: Configure named.conf.options
      template:
        src: named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: bind
        group: bind
        mode: 0644

    - name: Configure zone file for local domain
      template:
        src: db.example.com.j2
        dest: /etc/bind/db.example.com
        owner: bind
        group: bind
        mode: 0644

    - name: Configure named.conf.local
      template:
        src: named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: bind
        group: bind
        mode: 0644

    - name: Enable and start BIND9 server
      systemd:
        name: bind9
        enabled: yes
        state: started