---
- name: Install and Configure DHCP Server
  hosts: ubuntu_hosts
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install DHCP Server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Configure DHCP Server
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: 0644

    - name: Enable and start DHCP server
      systemd:
        name: isc-dhcp-server
        enabled: yes
        state: started